runtime: nodejs22
env: standard

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 3

env_variables:
  NODE_ENV: production
  # GEMINI_API_KEY will be set via gcloud deployment
  PORT: 8080

entrypoint: node server.js

handlers:
- url: /.*
  script: auto